### PR TITLE
Update overview to explain variable types

### PR DESCRIPTION
**Pull request by JeffFessler**
It took me some time to figure out the type requirements, so documenting it here (or somewhere) might help other users.

### CODE REVIEW

**Comment by tknopp** [comment]
thanks!

**Comment by tknopp** [comment]
@JeffFessler:
- I realized that we already have the wrapper functions that don't require the creation of a plan. They are now tested here:
https://github.com/tknopp/NFFT.jl/blob/master/test/test.jl#L38
- My recent commit now allows to mix types of the input vector and the plan. Most things should now just work.

**Comment by JeffFessler** [comment]
Great!  The plan version is more suitable for my needs.  I have finished my wrapper (thanks to your helpful feedback).  It is here in case you are curious how it looks with `LinearMaps.jl`:
https://github.com/JeffFessler/MIRT.jl/blob/master/src/nufft/nufft.jl
My convention goes from 0 to N-1 (with an optional shift) so you'll see phasors there...

**Comment by tknopp** [comment]
Nice, I will have a look. Its great that you use NFFT.jl in MIRT.jl. If you are missing something in NFFT.jl it would cool if we could work on this together within this package. The goal is kind of to have a rock solid NFFT Julia package.

I have granted you commit rights, so that you can make changes on your own. This is also very helpful, since you can work on a branch within the same repository without the need to switch the git URL.

**Comment by JeffFessler** [comment]
Thanks!

**Pull request merged**
