### PR TITLE
add CuNFFT

### PR DESCRIPTION
**Pull request by migrosser**
This pull requests proposes a CUDA-implementation of the NFFT. The implementation is based on a dedication `CuNFFTPlan`, which does not interfere with the already existing `NFFTPlan`. So far the implementation supports NFFTS in 1d, 2d and 3d.

### CODE REVIEW

**Comment by JeffFessler** [comment]
It will be great to have CUDA support!
Personally as a user I would prefer that I could enable/disable CUDA version by using multiple dispatch,
e.g., setting a flag like `NFFTPlan( ... ; gpu=:cuda)` instead of exporting a separate function name like `CuNFFTPlan`.
But that's just my view and I'll let the two of you work it out.
I suppose it is easy to add the flag to NFFTPlan later.

**Comment by tknopp** [comment]
I have to think about the interface on this myself a little bit. More opinions are very much appreciated Jeff. We want this package to satisfy a broad user audience (and especially those with NuFFT background)

The first question is, whether it is possible to have a single type for both the CPU and the GPU code. If I see it correctly this is not really possible since the CUDA types are simply different from the CPU types. We may introduce a new template parameter to share the same code but the type will still be different.

The other question (which is independent) is, how the public interface should look like. The signature  `NFFTPlan( ... ; gpu=:cuda)` could work on top of what we have now. `NFFTPlan` would than basically be a factory method. The downside of using `gpu=:cuda` is that the constructor becomes type instable since the return type depends on the value of `gpu`. But if we want to be able of changing the backend dynamically this needs to be at some point...

**Comment by JeffFessler** [comment]
Good point about type stability.  I hadn't thought about that.  I'm not sure how much it matters at a top "plan" level compared to the lower level code that does the real work.  Perhaps it is better to start with the separate interface and users could always "overload" `NUFFTPlan` themselves with an extra argument if they really want.  Hopefully after the "plan" is done the rest of the interface looks identical (I didn't check).

BTW, I suggested `gpu=:cuda` not `cuda=true` because I hope someday there might be `gpu=:opencl` or some other alternative to a single vendor's proprietary language!

**Comment by migrosser** [comment]
yes, after plan creation the interface looks the same. I guess that the type-instability wouldn't hurt too much especially in the case that one reuses a plan to compute multiple NFFTs. However, the separate interfaces also seemed like a "safer" starting point to me, which is why I didn't do more work towards a unified interface so far.

**Comment by hofmannmartin** [comment]
One could solve the type instability problem by something like this
```julia
abstract type FFTKernel end

struct JuliaKernel <: FFTKernel; end
struct CUDAKernel <: FFTKernel; end

function NFFTPlan(::Type{T}=JuliaKernel, ... ) where {T<:FFTKernel}
...
end
```

This would also make it quite easy to add things like opencl in the future.

**Comment by tknopp** [comment]
Yes, this would be the typical way of getting this type stable but I am actually not 100% sure what we would really gain from that. The type instability of the constructor is certainly not a real issue. The real issue is more what you write if you want to embed the NFFT type into another struct:
```
struct HighLevelMRIRecon
  nfftPlan::???
end
```
I know one can do 
```
struct HighLevelMRIRecon{U}
  nfftPlan::U
end
```
but that can complicate things in upper levels of the software stack. 

But maybe we should look at what others have done. https://github.com/JuliaMath/AbstractFFTs.jl is certainly something we should have a look at.

**Comment by tknopp** [comment]
> Hopefully after the "plan" is done the rest of the interface looks identical

I have not checked either, but that is certainly a mandatory thing. In the end we need some `AbstractNFFT` with a proper defined interface.

**Comment by hofmannmartin** [comment]
So a `abstract type NFFTPlans{T,D,DN} end` with `CuNFFTPlan{T,D,DN}<:NFFTPlans{T,D,DN}`?

**Comment by tknopp** [comment]
yes, kindof. This is similar as is done for the FFT. Here are the CPU and the CUDA version:

https://github.com/JuliaMath/FFTW.jl/blob/master/src/fft.jl#L225
https://github.com/JuliaGPU/CUDA.jl/blob/6ea1494395644a11833c50f45e820fb756443a1e/lib/cufft/fft.jl#L20

They use the more general type `Plan{T}`, but I would want something more specific.

**Comment by migrosser** [comment]
Ok, we now have an abstract type `AbstractNFFTPlan{D,DIM,T}`, which defines an interface for all concrete implementations. All actual NFFPlans need to implement the in-place methods `nfft!(p,f,fhat)` and `nfft_adjoint!(p,fHat,f)`. The remaining functions are then automatically derived.
To create a plan, there is a factory method `plan_nfft(x,N,...; device=CPU)`. The kind of plan to be created can thus be specified by setting `device=CPU` or `device=CUDAGPU`.

**Comment by migrosser** [comment]
One remaining issue is that the tests of the CuNFFT are apparently not run by appveyor. I guess this happens because `CUDA.functional()` returns `false` for their setup. Any ideas on how to fix this?
I checked how CUDA.jl does its testing but they are using Buildkite instead of travis and appveyor.

**Comment by tknopp** [comment]
where are are Travis tests? I cannot see them.

**Comment by tknopp** [comment]
Ok, I am merging this now since it looks all good to me.

For reference: We need to work on a more generic way for the directional NFFT. From an interface point of view FFTW.jl has solved this much nicer (although the two are not exactly comparable). But: this is orthogonal to this present PR and work for the future.

**Pull request merged**
