### PR TITLE
floor and round with Julia v0.4 syntax

### PR DESCRIPTION
**Pull request by robertdj**
This may be a little early as the changes are not compatible with Julia v0.3...

### CODE REVIEW

**Comment by tknopp** [comment]
@robertdj: Thank, do you need this before 0.4 is released? In that case a dual compatibility could be reached using the Compat package. Unfortunately I have not to much time to maintain this package currently but will of course merge PR of you. Do you actively use this package?

**Comment by robertdj** [comment]
I am just starting to use the package, but I expect it to be very important to me. 
I don't need this before 0.4 is released.

**Comment by tknopp** [comment]
Cool! I will then merge your PR once 0.4 is out. Please raise issues if you find something that doesn't fit your needs

**Comment by robertdj** [comment]
I just tested on Julia v0.4.0 and everything passes. Can you merge now? 
Is it okay to add a tag with `v0.0.2` to indicate ArrayViews support?

**Pull request merged**
