### PR TITLE
Add ndft! and ndft_adjoint!

### PR DESCRIPTION
**Pull request by JeffFessler**
To be honest I started this because I didn't see `nfft!` documented and I thought it would be easier to start with a a `ndft!` version.  After I finished this I noticed that `nfft!` does exist.  I had even searched the repo for `nfft!` with github's search bar but oddly it did not find it.
Admittedly an in-place version of DFT is not so essential, but let's see what you think...

Also, the `SpecialFunctions` was pinned to an old version that caused me some issues so I bumped that up.

### CODE REVIEW

**Comment by JeffFessler** [comment]
I guess whether it is a draft or not is in the eye of the beholder.  But I also want to see what happens with the code coverage.  I think it will be unchanged...

**Comment by tknopp** [comment]
I am fine with adding these functions, alltough I would ne recommend using them ;-)

Thanks also for the Version bumps. We need that bot that does this automatically. Will add that later.

**Comment by JeffFessler** [comment]
One possible version bump option is this, but I have not tried it:
https://github.com/bcbi/CompatHelper.jl

**Comment by tknopp** [comment]
Yes that's what I learned about a week ago and it seems to do actually exactly what it is supposed to do. I have to admit that the upper bounding is a pretty large paradigm shift I was first struggling with, but in the end its the only that makes sense. 

I triggered the release, so you get ya new bounds soon.

**Comment by JeffFessler** [comment]
I agree that it seems counter-intuitive.  Thanks!

**Pull request merged**
